#!/usr/bin/env python3
"""
porthole - manage FRP tunnel services

Usage:
  python porthole.py config                   # show current config
  python porthole.py config --vps IP          # set VPS host
  python porthole.py config --token TOKEN     # set FRP token (both .env files)
  python porthole.py config --dashboard PWD   # set dashboard password
  python porthole.py config --rotate-token    # generate a new token automatically
  python porthole.py list
  python porthole.py add <name> <local_port> <remote_port> [--docker <container>]
  python porthole.py remove <name>
  python porthole.py sync
  python porthole.py status
"""

import argparse
import os
import secrets
import socket
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).parent
SERVICES_CONF = ROOT / "services.conf"
LOCAL_ENV     = ROOT / "local" / ".env"
VPS_ENV       = ROOT / "vps"   / ".env"
FRPC_INI      = ROOT / "local" / "frpc.ini"
VPS_COMPOSE   = ROOT / "vps"   / "docker-compose.yml"
SSH_KEY       = Path.home() / ".ssh" / "porthole_do"

# ── Colours (no deps) ─────────────────────────────────────────────────────────
def _c(code, text): return f"\033[{code}m{text}\033[0m" if sys.stdout.isatty() else text
green  = lambda t: _c("32", t)
red    = lambda t: _c("31", t)
yellow = lambda t: _c("33", t)
bold   = lambda t: _c("1",  t)
dim    = lambda t: _c("2",  t)

# ── Data ──────────────────────────────────────────────────────────────────────
@dataclass
class Service:
    name: str
    local_port: int
    remote_port: int
    local_host: str = ""

def load_env(path: Path) -> dict:
    env = {}
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env

def save_env(path: Path, updates: dict):
    """Update or add keys in a .env file, creating it if needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    written = set()
    new_lines = []
    for line in lines:
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            k = stripped.split("=", 1)[0].strip()
            if k in updates:
                new_lines.append(f"{k}={updates[k]}")
                written.add(k)
                continue
        new_lines.append(line)
    for k, v in updates.items():
        if k not in written:
            new_lines.append(f"{k}={v}")
    path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")

def load_services() -> list:
    services = []
    for line in SERVICES_CONF.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parts = [p.strip() for p in stripped.split(":")]
        if len(parts) < 3 or not parts[1].isdigit() or not parts[2].isdigit():
            continue
        services.append(Service(
            name       = parts[0],
            local_port = int(parts[1]),
            remote_port= int(parts[2]),
            local_host = parts[3] if len(parts) > 3 else "",
        ))
    return services

# ── Generators ────────────────────────────────────────────────────────────────
def gen_frpc_ini(services, vps_host, frp_token) -> str:
    lines = [
        "# AUTO-GENERATED by porthole.py — run: python porthole.py sync",
        "",
        "[common]",
        f"server_addr = {vps_host}",
        "server_port = 7000",
        f"token       = {frp_token}",
        "log_file    = /dev/stdout",
        "log_level   = info",
    ]
    for svc in services:
        lhost = svc.local_host or "host.docker.internal"
        lines += ["", f"[{svc.name}]", "type        = tcp",
                  f"local_ip    = {lhost}", f"local_port  = {svc.local_port}",
                  f"remote_port = {svc.remote_port}"]
    return "\n".join(lines) + "\n"

def gen_vps_compose(services) -> str:
    ports = [
        '      - "7000:7000"  # frp control',
        '      - "7500:7500"  # dashboard',
    ]
    for svc in services:
        ports.append(f'      - "{svc.remote_port}:{svc.remote_port}"  # {svc.name}')
    return (
        "# AUTO-GENERATED by porthole.py — run: python porthole.py sync\n\n"
        "services:\n  frps:\n    image: snowdreamtech/frps:0.51.3\n"
        "    restart: unless-stopped\n    volumes:\n"
        "      - ./frps.ini:/etc/frp/frps.ini:ro\n    ports:\n"
        + "\n".join(ports)
        + "\n    command: frps -c /etc/frp/frps.ini\n"
    )

# ── Helpers ───────────────────────────────────────────────────────────────────
def run(cmd: str, silent=False):
    kwargs = dict(shell=True, capture_output=True, text=True) if silent else dict(shell=True)
    return subprocess.run(cmd, **kwargs)

def ssh(host, cmd):
    return run(f'ssh -i "{SSH_KEY}" -o StrictHostKeyChecking=no root@{host} "{cmd}"')

def scp_file(src: Path, host, remote_path):
    return run(f'scp -i "{SSH_KEY}" "{src}" root@{host}:{remote_path}')

def port_open(host, port, timeout=3) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except Exception:
        return False

def sync_firewall(services):
    result = run("doctl compute firewall list --format ID,Name --no-header", silent=True)
    if result.returncode != 0:
        print(f"  {yellow('⚠')}  doctl not available — skipping firewall sync")
        return
    fw_lines = [l for l in result.stdout.splitlines() if "porthole-fw" in l]
    if not fw_lines:
        print(f"  {yellow('⚠')}  porthole-fw firewall not found — skipping firewall sync")
        return
    fw_id = fw_lines[0].split()[0]
    rules  = "protocol:tcp,ports:22,address:0.0.0.0/0,address:::/0"
    rules += " protocol:tcp,ports:7000,address:0.0.0.0/0,address:::/0"
    rules += " protocol:tcp,ports:7500,address:0.0.0.0/0,address:::/0"
    for svc in services:
        rules += f" protocol:tcp,ports:{svc.remote_port},address:0.0.0.0/0,address:::/0"
    out_rules = "protocol:tcp,ports:all,address:0.0.0.0/0,address:::/0 protocol:udp,ports:all,address:0.0.0.0/0,address:::/0"
    run(f'doctl compute firewall update {fw_id} --name porthole-fw --inbound-rules "{rules}" --outbound-rules "{out_rules}"', silent=True)
    ports_str = ", ".join(str(s.remote_port) for s in services)
    print(f"  {green('✓')}  firewall synced (22, 7000, 7500, {ports_str})")

# ── Commands ──────────────────────────────────────────────────────────────────
def cmd_config(args):
    env_local = load_env(LOCAL_ENV)
    env_vps   = load_env(VPS_ENV)
    changed   = False

    if args.vps:
        save_env(LOCAL_ENV, {"VPS_HOST": args.vps})
        print(f"  {green('✓')}  VPS_HOST  →  {bold(args.vps)}")
        changed = True

    if args.token:
        save_env(LOCAL_ENV, {"FRP_TOKEN": args.token})
        save_env(VPS_ENV,   {"FRP_TOKEN": args.token})
        print(f"  {green('✓')}  FRP_TOKEN updated in local/.env and vps/.env")
        changed = True

    if args.rotate_token:
        token = secrets.token_hex(32)
        save_env(LOCAL_ENV, {"FRP_TOKEN": token})
        save_env(VPS_ENV,   {"FRP_TOKEN": token})
        print(f"  {green('✓')}  FRP_TOKEN rotated  →  {token}")
        print(f"  {yellow('!')}  Run 'python porthole.py sync' then redeploy frps on the VPS")
        changed = True

    if args.dashboard:
        save_env(VPS_ENV, {"DASHBOARD_PWD": args.dashboard})
        print(f"  {green('✓')}  DASHBOARD_PWD updated in vps/.env")
        changed = True

    if not changed:
        # Show current config
        env = {**env_local, **env_vps}
        vps   = env.get("VPS_HOST",      dim("not set"))
        token = env.get("FRP_TOKEN",     "")
        dash  = env.get("DASHBOARD_PWD", dim("not set"))
        token_display = (token[:8] + "..." + token[-4:]) if token else dim("not set")
        print(f"\n  {bold('Current config')}\n")
        print(f"  {'VPS_HOST':<18}  {bold(vps)}")
        print(f"  {'FRP_TOKEN':<18}  {token_display}  {dim('(masked)')}")
        print(f"  {'DASHBOARD_PWD':<18}  {'*' * 8 if dash != dim('not set') else dash}")
        print(f"\n  {dim('Dashboard:')}  http://{env.get('VPS_HOST','?')}:7500")
        print(f"\n  {dim('To change values:')}")
        print(f"  python porthole.py config --vps <IP>")
        print(f"  python porthole.py config --token <TOKEN>")
        print(f"  python porthole.py config --dashboard <PASSWORD>")
        print(f"  python porthole.py config --rotate-token\n")

def cmd_list(_args):
    services = load_services()
    env = load_env(LOCAL_ENV)
    vps = env.get("VPS_HOST", dim("not set"))
    print(f"\n  VPS: {bold(vps)}\n")
    print(f"  {bold('NAME'):<28}  {bold('LOCAL'):<30}  {bold('VPS PORT')}")
    print(f"  {'-'*26}  {'-'*28}  {'-'*8}")
    for svc in services:
        lhost = svc.local_host or "host.docker.internal"
        print(f"  {svc.name:<26}  {lhost}:{svc.local_port:<22}  :{svc.remote_port}")
    print()

def cmd_add(args):
    content = SERVICES_CONF.read_text(encoding="utf-8")
    services = load_services()
    if any(s.name == args.name for s in services):
        print(f"  {red('✗')}  Service '{args.name}' already exists. Remove it first.")
        sys.exit(1)
    lhost_part = f" : {args.docker}" if args.docker else ""
    entry = f"{args.name:<16}: {args.local_port:<6}: {args.remote_port}{lhost_part}"
    SERVICES_CONF.write_text(content.rstrip() + f"\n{entry}\n", encoding="utf-8")
    print(f"  {green('✓')}  Added: {bold(entry)}")
    if not getattr(args, "no_sync", False):
        cmd_sync(args)

def cmd_remove(args):
    lines = SERVICES_CONF.read_text(encoding="utf-8").splitlines()
    new_lines, removed = [], False
    for line in lines:
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            name = stripped.split(":")[0].strip()
            if name == args.name:
                removed = True
                continue
        new_lines.append(line)
    if not removed:
        print(f"  {red('✗')}  Service '{args.name}' not found.")
        sys.exit(1)
    SERVICES_CONF.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    print(f"  {green('✓')}  Removed: {bold(args.name)}")
    if not getattr(args, "no_sync", False):
        cmd_sync(args)

def cmd_sync(_args):
    print()
    env  = {**load_env(LOCAL_ENV), **load_env(VPS_ENV)}
    vps_host  = env.get("VPS_HOST",  "")
    frp_token = env.get("FRP_TOKEN", "")
    services  = load_services()

    # 1. local/frpc.ini
    FRPC_INI.write_text(gen_frpc_ini(services, vps_host, frp_token), encoding="utf-8")
    print(f"  {green('✓')}  local/frpc.ini")

    # 2. vps/docker-compose.yml
    VPS_COMPOSE.write_text(gen_vps_compose(services), encoding="utf-8")
    print(f"  {green('✓')}  vps/docker-compose.yml")

    # 3. Push to VPS + restart frps
    if vps_host and SSH_KEY.exists():
        scp_file(VPS_COMPOSE, vps_host, "~/porthole/vps/docker-compose.yml")
        ssh(vps_host, "cd ~/porthole/vps && docker compose up -d --quiet-pull 2>/dev/null")
        print(f"  {green('✓')}  VPS updated & frps restarted")
    else:
        print(f"  {yellow('⚠')}  SSH key or VPS_HOST missing — skipping VPS push")
        print(f"       Manually run: scp vps/docker-compose.yml root@VPS:~/porthole/vps/")

    # 4. Sync DO firewall
    sync_firewall(services)

    # 5. Restart local frpc if Docker is available
    result = run("docker compose -f local/docker-compose.yml up -d --force-recreate frpc", silent=True)
    if result.returncode == 0:
        print(f"  {green('✓')}  local frpc restarted")
    else:
        print(f"  {yellow('⚠')}  Docker not running locally — restart frpc manually")

    print(f"\n  {bold('Services configured')} ({len(services)}):")
    for svc in services:
        lhost = svc.local_host or "host.docker.internal"
        print(f"    {svc.name:<20}  {lhost}:{svc.local_port}  →  {vps_host}:{svc.remote_port}")
    print()

def cmd_status(_args):
    env      = load_env(LOCAL_ENV)
    vps_host = env.get("VPS_HOST", "")
    services = load_services()
    if not vps_host:
        print(f"  {red('✗')}  VPS_HOST not set in local/.env")
        return
    print(f"\n  Checking {bold(vps_host)}...\n")

    # frp control port
    ctrl = port_open(vps_host, 7000)
    print(f"  {green('✓') if ctrl else red('✗')}  frps control  :{7000}")

    for svc in services:
        up = port_open(vps_host, svc.remote_port)
        icon = green("✓") if up else red("✗")
        url  = f"http://{vps_host}:{svc.remote_port}"
        print(f"  {icon}  {svc.name:<20}  {url}")
    print()

# ── Entry point ───────────────────────────────────────────────────────────────
def main():
    p = argparse.ArgumentParser(
        prog="porthole",
        description="Manage FRP tunnel services",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "examples:\n"
            "  python porthole.py list\n"
            "  python porthole.py add fastapi 8000 8000\n"
            "  python porthole.py add mydb 5432 5432 --docker postgres\n"
            "  python porthole.py remove fastapi\n"
            "  python porthole.py sync\n"
            "  python porthole.py status\n"
        ),
    )
    sub = p.add_subparsers(dest="cmd", metavar="command")

    pc = sub.add_parser("config", help="Show or update VPS/token/dashboard config")
    pc.add_argument("--vps",           metavar="IP_OR_HOST", help="Set VPS host")
    pc.add_argument("--token",         metavar="TOKEN",       help="Set FRP shared token")
    pc.add_argument("--dashboard",     metavar="PASSWORD",    help="Set dashboard password")
    pc.add_argument("--rotate-token",  action="store_true",   help="Generate a new random token")

    sub.add_parser("list",   help="List configured services")
    sub.add_parser("sync",   help="Regenerate configs, push to VPS, sync firewall")
    sub.add_parser("status", help="Check tunnel health for each service")

    pa = sub.add_parser("add", help="Add a service and sync")
    pa.add_argument("name")
    pa.add_argument("local_port",  type=int)
    pa.add_argument("remote_port", type=int)
    pa.add_argument("--docker",    metavar="CONTAINER", help="Docker service name if running in compose")
    pa.add_argument("--no-sync",   action="store_true",  help="Skip sync after adding")

    pr = sub.add_parser("remove", help="Remove a service and sync")
    pr.add_argument("name")
    pr.add_argument("--no-sync", action="store_true", help="Skip sync after removing")

    args = p.parse_args()
    dispatch = {"config": cmd_config, "list": cmd_list, "add": cmd_add,
                "remove": cmd_remove, "sync": cmd_sync, "status": cmd_status}
    fn = dispatch.get(args.cmd)
    if fn:
        fn(args)
    else:
        p.print_help()

if __name__ == "__main__":
    main()
