#!/usr/bin/env bash
# setup.sh — reads services.conf and regenerates local/frpc.ini + vps/docker-compose.yml
# Run this every time you add, remove, or change a service.
set -euo pipefail
cd "$(dirname "$0")"

CONF="services.conf"

if [[ ! -f "$CONF" ]]; then
  echo "Error: $CONF not found. Run this script from the project root." >&2
  exit 1
fi

# Load .env files so VPS_HOST / FRP_TOKEN are available if already configured
if [[ -f local/.env ]]; then set -a; source local/.env; set +a; fi
if [[ -f vps/.env   ]]; then set -a; source vps/.env;   set +a; fi

VPS_HOST="${VPS_HOST:-YOUR_VPS_IP}"
FRP_TOKEN="${FRP_TOKEN:-YOUR_FRP_TOKEN}"

# ── Parse services.conf into arrays ──────────────────────────────────────────
declare -a NAMES LPORTS RPORTS LHOSTS

while IFS=':' read -r col1 col2 col3 col4 _rest; do
  name=$(printf '%s' "$col1"     | xargs)
  lport=$(printf '%s' "$col2"    | xargs)
  rport=$(printf '%s' "$col3"    | xargs)
  lhost=$(printf '%s' "${col4:-}" | xargs)

  # skip blank lines and comments
  [[ -z "$name" || "$name" == \#* ]] && continue

  if [[ -z "$lport" || -z "$rport" ]]; then
    echo "Warning: skipping malformed line (need name:local_port:remote_port): $col1" >&2
    continue
  fi

  # default local_host to host.docker.internal (the host machine)
  NAMES+=("$name")
  LPORTS+=("$lport")
  RPORTS+=("$rport")
  LHOSTS+=("${lhost:-host.docker.internal}")
done < "$CONF"

if [[ ${#NAMES[@]} -eq 0 ]]; then
  echo "Warning: no services found in $CONF — nothing to generate." >&2
  exit 0
fi

# ── 1. Generate local/frpc.ini ───────────────────────────────────────────────
{
  printf '# AUTO-GENERATED by setup.sh — edit services.conf and re-run ./setup.sh\n\n'
  printf '[common]\nserver_addr = %s\nserver_port = 7000\ntoken       = %s\nlog_file    = /dev/stdout\nlog_level   = info\n' \
    "$VPS_HOST" "$FRP_TOKEN"

  for i in "${!NAMES[@]}"; do
    printf '\n[%s]\ntype        = tcp\nlocal_ip    = %s\nlocal_port  = %s\nremote_port = %s\n' \
      "${NAMES[$i]}" "${LHOSTS[$i]}" "${LPORTS[$i]}" "${RPORTS[$i]}"
  done
} > local/frpc.ini

echo "✓  local/frpc.ini"

# ── 2. Generate vps/docker-compose.yml ──────────────────────────────────────
{
  printf '# AUTO-GENERATED by setup.sh — edit services.conf and re-run ./setup.sh\n\n'
  printf 'services:\n'
  printf '  frps:\n'
  printf '    image: snowdreamtech/frps:0.51.3\n'
  printf '    restart: unless-stopped\n'
  printf '    volumes:\n'
  printf '      - ./frps.ini:/etc/frp/frps.ini:ro\n'
  printf '    ports:\n'
  printf '      - "7000:7000"  # frp control\n'
  printf '      - "7500:7500"  # dashboard\n'

  for i in "${!NAMES[@]}"; do
    printf '      - "%s:%s"  # %s\n' "${RPORTS[$i]}" "${RPORTS[$i]}" "${NAMES[$i]}"
  done

  printf '    command: frps -c /etc/frp/frps.ini\n'
} > vps/docker-compose.yml

echo "✓  vps/docker-compose.yml"

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo "Services configured (${#NAMES[@]}):"
printf '  %-20s  %-22s  %s\n' "NAME" "LOCAL" "VPS PORT"
printf '  %-20s  %-22s  %s\n' "----" "-----" "--------"
for i in "${!NAMES[@]}"; do
  printf '  %-20s  %-12s →  :%s\n' \
    "${NAMES[$i]}" "${LHOSTS[$i]}:${LPORTS[$i]}" "${RPORTS[$i]}"
done

# ── 3. Sync DigitalOcean firewall (if doctl is available) ────────────────────
if command -v doctl &>/dev/null && doctl account get &>/dev/null 2>&1; then
  FW_ID=$(doctl compute firewall list --format ID,Name --no-header 2>/dev/null | grep porthole-fw | awk '{print $1}')
  if [[ -n "$FW_ID" ]]; then
    # Always keep SSH + frp control + dashboard, then add all service ports
    RULES="protocol:tcp,ports:22,address:0.0.0.0/0,address:::/0"
    RULES="$RULES protocol:tcp,ports:7000,address:0.0.0.0/0,address:::/0"
    RULES="$RULES protocol:tcp,ports:7500,address:0.0.0.0/0,address:::/0"
    for i in "${!RPORTS[@]}"; do
      RULES="$RULES protocol:tcp,ports:${RPORTS[$i]},address:0.0.0.0/0,address:::/0"
    done
    doctl compute firewall update "$FW_ID" \
      --name porthole-fw \
      --inbound-rules  "$RULES" \
      --outbound-rules "protocol:tcp,ports:all,address:0.0.0.0/0,address:::/0 protocol:udp,ports:all,address:0.0.0.0/0,address:::/0" \
      > /dev/null
    echo "✓  firewall synced (ports: 22, 7000, 7500$(printf ', %s' "${RPORTS[@]}"))"
  else
    echo "⚠  doctl found but no 'porthole-fw' firewall — skipping firewall sync"
  fi
fi

echo ""
echo "Next steps:"
echo "  1. Reload local frpc:    docker compose -f local/docker-compose.yml up -d --force-recreate frpc"
echo "  2. Push & reload VPS:    scp -r vps/ root@\$VPS_HOST:~/proxy/ && \\"
echo "                           ssh root@\$VPS_HOST 'cd ~/proxy/vps && docker compose up -d'"
