import sys
from dataclasses import dataclass
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT             = Path(__file__).parent.parent
SERVICES_CONF    = ROOT / "services.conf"
LOCAL_ENV        = ROOT / "local" / ".env"
VPS_ENV          = ROOT / "vps"   / ".env"
FRPC_INI         = ROOT / "local" / "frpc.ini"
VPS_COMPOSE      = ROOT / "vps"   / "docker-compose.yml"
_DEFAULT_SSH_KEY = Path.home() / ".ssh" / "porthole_do"

# ── Colours ───────────────────────────────────────────────────────────────────
def _c(code, t): return f"\033[{code}m{t}\033[0m" if sys.stdout.isatty() else t
green  = lambda t: _c("32", t)
red    = lambda t: _c("31", t)
yellow = lambda t: _c("33", t)
bold   = lambda t: _c("1",  t)
dim    = lambda t: _c("2",  t)

# ── Data ──────────────────────────────────────────────────────────────────────
@dataclass
class Service:
    name:       str
    local_port: int
    remote_port: int
    local_host: str = ""

def load_env(path: Path) -> dict:
    env = {}
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env

def save_env(path: Path, updates: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    lines   = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    written = set()
    out     = []
    for line in lines:
        s = line.strip()
        if s and not s.startswith("#") and "=" in s:
            k = s.split("=", 1)[0].strip()
            if k in updates:
                out.append(f"{k}={updates[k]}")
                written.add(k)
                continue
        out.append(line)
    for k, v in updates.items():
        if k not in written:
            out.append(f"{k}={v}")
    path.write_text("\n".join(out) + "\n", encoding="utf-8")

def get_ssh_key() -> Path:
    env = load_env(LOCAL_ENV)
    return Path(env["SSH_KEY"]).expanduser() if env.get("SSH_KEY") else _DEFAULT_SSH_KEY

def load_services() -> list:
    services = []
    for line in SERVICES_CONF.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        parts = [p.strip() for p in s.split(":")]
        if len(parts) < 3 or not parts[1].isdigit() or not parts[2].isdigit():
            continue
        services.append(Service(
            name        = parts[0],
            local_port  = int(parts[1]),
            remote_port = int(parts[2]),
            local_host  = parts[3] if len(parts) > 3 else "",
        ))
    return services

# ── Generators ────────────────────────────────────────────────────────────────
def gen_frpc_ini(services, vps_host, frp_token) -> str:
    lines = [
        "# AUTO-GENERATED by porthole.py — run: python porthole.py sync",
        "", "[common]",
        f"server_addr = {vps_host}",
        "server_port = 7000",
        f"token       = {frp_token}",
        "log_file    = /dev/stdout",
        "log_level   = info",
    ]
    for svc in services:
        lhost = svc.local_host or "host.docker.internal"
        lines += ["", f"[{svc.name}]", "type        = tcp",
                  f"local_ip    = {lhost}", f"local_port  = {svc.local_port}",
                  f"remote_port = {svc.remote_port}"]
    return "\n".join(lines) + "\n"

def gen_vps_compose(services) -> str:
    ports = ['      - "7000:7000"  # frp control', '      - "7500:7500"  # dashboard']
    for svc in services:
        ports.append(f'      - "{svc.remote_port}:{svc.remote_port}"  # {svc.name}')
    return (
        "# AUTO-GENERATED by porthole.py — run: python porthole.py sync\n\n"
        "services:\n  frps:\n    image: snowdreamtech/frps:0.51.3\n"
        "    restart: unless-stopped\n    volumes:\n"
        "      - ./frps.ini:/etc/frp/frps.ini:ro\n    ports:\n"
        + "\n".join(ports) + "\n    command: frps -c /etc/frp/frps.ini\n"
    )

def gen_nginx_conf(domain, services) -> str:
    locations = ""
    for svc in services:
        locations += (
            f"\n    # {svc.name}\n"
            f"    location /{svc.name}/ {{\n"
            f"        proxy_pass http://127.0.0.1:{svc.remote_port}/;\n"
            f"        proxy_set_header Host $host;\n"
            f"        proxy_set_header X-Real-IP $remote_addr;\n"
            f"        proxy_set_header X-Forwarded-Proto $scheme;\n"
            f"        proxy_http_version 1.1;\n"
            f"        proxy_set_header Upgrade $http_upgrade;\n"
            f"        proxy_set_header Connection \"upgrade\";\n"
            f"        proxy_read_timeout 86400s;\n"
            f"        proxy_send_timeout 86400s;\n"
            f"        proxy_buffering off;\n"
            f"    }}\n"
        )
    return (
        f"server {{\n"
        f"    listen 80;\n"
        f"    server_name {domain};\n"
        f"    return 301 https://$host$request_uri;\n"
        f"}}\n\n"
        f"server {{\n"
        f"    listen 443 ssl;\n"
        f"    server_name {domain};\n\n"
        f"    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;\n"
        f"    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;\n"
        f"    include /etc/letsencrypt/options-ssl-nginx.conf;\n"
        f"    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;\n"
        f"{locations}}}\n"
    )
