def gen_frpc_ini(services, vps_host, frp_token) -> str:
    lines = [
        "# AUTO-GENERATED by porthole.py — run: python porthole.py sync",
        "", "[common]",
        f"server_addr = {vps_host}",
        "server_port = 7000",
        f"token       = {frp_token}",
        "log_file    = /dev/stdout",
        "log_level   = info",
    ]
    for svc in services:
        lhost = svc.local_host or "host.docker.internal"
        lines += ["", f"[{svc.name}]", "type        = tcp",
                  f"local_ip    = {lhost}", f"local_port  = {svc.local_port}",
                  f"remote_port = {svc.remote_port}"]
    return "\n".join(lines) + "\n"

def gen_vps_compose(services) -> str:
    ports = ['      - "7000:7000"  # frp control', '      - "7500:7500"  # dashboard']
    for svc in services:
        ports.append(f'      - "{svc.remote_port}:{svc.remote_port}"  # {svc.name}')
    return (
        "# AUTO-GENERATED by porthole.py — run: python porthole.py sync\n\n"
        "services:\n  frps:\n    image: snowdreamtech/frps:0.51.3\n"
        "    restart: unless-stopped\n    volumes:\n"
        "      - ./frps.ini:/etc/frp/frps.ini:ro\n    ports:\n"
        + "\n".join(ports) + "\n    command: frps -c /etc/frp/frps.ini\n"
    )

def gen_nginx_conf(domain, services) -> str:
    locations = ""
    for svc in services:
        locations += (
            f"\n    # {svc.name}\n"
            f"    location /{svc.name}/ {{\n"
            f"        proxy_pass http://127.0.0.1:{svc.remote_port}/;\n"
            f"        proxy_set_header Host $host;\n"
            f"        proxy_set_header X-Real-IP $remote_addr;\n"
            f"        proxy_set_header X-Forwarded-Proto $scheme;\n"
            f"        proxy_http_version 1.1;\n"
            f"        proxy_set_header Upgrade $http_upgrade;\n"
            f"        proxy_set_header Connection \"upgrade\";\n"
            f"        proxy_read_timeout 86400s;\n"
            f"        proxy_send_timeout 86400s;\n"
            f"        proxy_buffering off;\n"
            f"    }}\n"
        )
    return (
        f"server {{\n    listen 80;\n    server_name {domain};\n"
        f"    return 301 https://$host$request_uri;\n}}\n\n"
        f"server {{\n    listen 443 ssl;\n    server_name {domain};\n\n"
        f"    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;\n"
        f"    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;\n"
        f"    include /etc/letsencrypt/options-ssl-nginx.conf;\n"
        f"    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;\n"
        f"{locations}}}\n"
    )
